query {
  usuarios {
    ...userPersonalData
    ativo
    salario
    tecnologias
    telefone
  }

  produtos{
    nome
    preco
  }

  usuario(id: 3, nome: "Teste"){
    ...userPersonalData
  }

  primeiro: usuario(id: 1){
    ...userPersonalData
  }

  segundo: usuario(id: 2){
    ...userPersonalData
  }
}

fragment userPersonalData on Usuario{
  nome
  idade
  telefone
}